# Build stage
FROM golang:1.24.4-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY *.go ./
RUN go build -o http-server-projeto-korp main.go

# Run stage
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/http-server-projeto-korp .
EXPOSE 8080
CMD ["./http-server-projeto-korp"]
