# Build stage
# https://hub.docker.com/layers/library/golang/1.25-alpine/images/sha256-a7a64bfb3b8a4724993e1c49d01ad331b5d8bc52461b3ecf89e9aedf3aadc635
FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY *.go ./
RUN go build -o http-server-projeto-korp main.go

# Run stage
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/http-server-projeto-korp .
EXPOSE 8080
CMD ["./http-server-projeto-korp"]
