---
- name: Provisionamento do Ambiente Projeto Korp - copiar chaves de autenticação ssh primeiro!
  hosts: proxmox_vm
  become: yes
  tasks:
    - name: Instalar dependências iniciais
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
        state: present
        update_cache: yes

    - name: Adicionar chave GPG do Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adicionar repositório do Docker
      apt_repository:
        #{{ ansible_distribution_release }} resolve automaticamente para 'noble', 'jammy', 'focal', etc.
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Instalar Docker e Docker Compose
      apt:
        name:
          - docker-ce
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Garantir que o serviço do Docker está rodando
      service:
        name: docker
        state: started
        enabled: yes

    - name: Criar diretório do projeto no servidor
      file:
        path: /opt/projeto-korp
        state: directory

    - name: Copiar arquivos do projeto para o servidor
      copy:
        src: ./
        dest: /opt/projeto-korp/

    - name: Construir imagens e subir containers com Docker Compose
      command: docker compose up -d --build
      args:
        chdir: /opt/projeto-korp

    - name: Aguardar o serviço inicializar
      pause:
        seconds: 5

    - name: Validar funcionamento do serviço com requisição HTTP 
      uri:
        url: http://localhost:80/projeto-korp
        return_content: yes
      register: api_response

    - name: Exibir resposta da validação no console 
      debug:
        msg: "Resposta do Serviço: {{ api_response.json }}"
