networks:
  korp-network:
    driver: bridge # Rede no modo bridge 

services:
  http-server-projeto-korp:
    build:
      context: ./app
      dockerfile: DockerFile
    networks:
      - korp-network
    

  nginx:
    image: nginx:latest 
    ports:
      - "80:80" 
    volumes:
      - ./config/nginx:/etc/nginx/conf.d/ 
    networks:
      - korp-network
    depends_on:
      - http-server-projeto-korp

